version: '3.3'
services:
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      back_net:
        aliases:
          - node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  post_db:
    env_file: 
      - .env
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net: 
        aliases:
          - post
  ui:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    env_file:
      - .env
    #build: ./ui
    image: ${USER_NAME}/ui:${APP_UI_VERSION}
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      back_net:
        aliases:
        - ui
      front_net:
        aliases:
        - ui
  post:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.pos
    env_file:
      - .env
    #build: ./post-py
    image: ${USER_NAME}/post:${APP_POST_VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    env_file:
      - .env
    #build: ./comment
    image: ${USER_NAME}/comment:${APP_COMMENT_VERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
volumes:
  post_db:

networks:
  back_net: 
  front_net:


