version: '3'
services: 
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back_net:
        aliases:
          - zipkin
  fluentd: 
    build: ../logging/fluentd
    ports: 
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
        aliases:
          - fluentd
  elasticsearch:
    networks:
      back_net:
        aliases:
          - elasticsearch
    image: elasticsearch:6.8.0
    expose: 
      - 9200
    ports:
      - "9200:9200"

  kibana:
    networks:
      back_net:
        aliases:
          - kibana
    image: kibana:6.8.0
    ports:
      - "5601:5601"

networks:
  back_net:
