#! /bin/bash

PROMETHEUS_PORT=9090; 			echo PROMETHEUS_PORT=$PROMETHEUS_PORT;
PROMETHEUS_CONTAINER_NAME=prometheus; 	echo PROMETHEUS_CONTAINER_NAME=$PROMETHEUS_CONTAINER_NAME
USER_NAME=garichsv;			echo USER_NAME=$USER_NAME


